(function(g){var window=this;'use strict';var R3=function(a){a.ma("cardstatechange",a.Oi()&&a.Ym()?1:0)},S3=function(a,b){var c=g.Ka(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},J7a=function(a){var b=g.Pl(a);
a=g.Sl(a);return new g.El(b.x,b.y,a.width,a.height)},K7a=function(a){return Math.pow(a,3)},L7a=function(a){return 3*a*a-2*a*a*a},V3=function(a){a=g.Oa(a);
delete T3[a];g.dd(T3)&&U3&&U3.stop()},N7a=function(){U3||(U3=new g.fo(function(){M7a()},20));
var a=U3;a.isActive()||a.start()},M7a=function(){var a=g.Ta();
g.Oc(T3,function(b){O7a(b,a)});
g.dd(T3)||N7a()},W3=function(a,b,c,d){g.Co.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.T=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},O7a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;P7a(a,a.progress);1==a.progress?(a.j=0,V3(a),a.onFinish(),a.NA()):a.Tc()&&a.zG()},P7a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.T[c]-a.u[c])*b+a.u[c]},Q7a=function(a,b){g.fb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},X3=function(a,b,c,d,e){W3.call(this,b,c,d,e);
this.element=a},R7a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
X3.call(this,a,b,c,d,e)},S7a=function(a){g.E.call(this);
this.u=a||window;this.j=[]},Y3=function(a){return a.baseUrl||null},Z3=function(a,b){return g.Cm(g.Ng(a,b),function(c){return!!c})},T7a=function(a,b,c){function d(V){var ea=V.hovercardButton;
if(!ea)return null;ea=ea.subscribeButtonRenderer;if(!ea)return null;var Q=f(ea.unsubscribedButtonText),pa=f(ea.subscribedButtonText);if(ea.subscribed){var fa=f(ea.subscriberCountWithUnsubscribeText);var ra=f(ea.subscriberCountText)}else fa=f(ea.subscriberCountText),ra=f(ea.subscriberCountWithSubscribeText);var Ma=null;if(V.signinEndpoint){Ma=S3(V,"signinEndpoint","webNavigationEndpointData","url");if(!Ma){var ib,va;Ma=null==(va=g.P(null==(ib=ea.signInEndpoint)?void 0:ib.commandMetadata,g.M2))?void 0:
va.url}if(!Ma)return null}return Q&&(pa||Ma)?{subscribed:ea.subscribed,subscribeText:Q,subscribeCount:fa,unsubscribeText:pa,unsubscribeCount:ra,enabled:ea.enabled,signinUrl:Ma,classic:V.useClassicSubscribeButton}:null}
function e(V){if(V){var ea=[],Q=V.videoId;Q&&ea.push("v="+Q);(Q=V.playlistId)&&ea.push("list="+Q);(V=V.startTimeSeconds)&&ea.push("t="+V);return"/watch?"+ea.join("&")}}
function f(V){if(!V)return null;var ea=V.simpleText;return ea?ea:V.runs?g.Ng(V.runs,function(Q){return Q.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,x=null,z=!1,B=null,C=null,G=null,F=null,K=null,L=null;if("VIDEO"===h)g.P(l,g.II)?m=g.P(l,g.II).url:(L=g.P(l,g.GH),m=e(L)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.P(l,g.II)?m=g.P(l,g.II).url:(L=g.P(l,g.GH),m=e(L)),n=!1,q=a,w=f(b.playlistLength);else if("CHANNEL"===
h){if(z=S3(l,"browseEndpoint","browseId"))x=z,m="/channel/"+x;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):C=f(b.subscribersText)}else"WEBSITE"===h?((G=S3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=S3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=S3(b,"title","accessibility","accessibilityData","label");var N=b.endpoint?b.endpoint.clickTrackingParams:null,
ba="";if(b.metadata){var S=f(b.metadata);S&&(ba=S)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ba,callToAction:f(b.callToAction),hQ:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,isLiveVideo:p,playlistLength:w,channelId:x,subscribeButton:B,subscribersText:C,isSubscribe:z,targetUrl:m||null,V_:n,sessionData:N?{itct:N}:null,Z4:q,Ry:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:Z3(b.impressionUrls||[],Y3),K_:Z3(b.hovercardShowUrls||[],Y3),clickUrls:Z3(l.loggingUrls||[],Y3),visualElement:g.Lz(b.trackingParams),productPrice:F,additionalFeesText:K,watchEndpoint:L||null}},U7a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:Z3(a.impressionUrls||[],Y3),elements:Z3(a.elements||[],function(d,e){return T7a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Lz(a.trackingParams));return c},V7a=function(a){g.TP.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Z=!0;this.I=0;a=a.V();this.T=g.IG(a)||"profilepage"===a.Ma;this.ea=a.experiments.eb("web_rounded_thumbnails");this.events=new g.vE(this);g.H(this,this.events);this.events.N(this.player,g.MA("creatorendscreen"),this.onCueRangeEnter);this.events.N(this.player,g.NA("creatorendscreen"),this.onCueRangeExit);this.events.N(this.player,"resize",this.Ab);this.events.N(window,"focus",this.Q3);this.load();var b=g.Ve("STYLE");(g.Le("HEAD")[0]||
document.body).appendChild(b);g.db(this,function(){g.af(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},W7a=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},$3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},X7a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=U7a(f,W7a(a))));a4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Zu;d&&(c.postParams={ad_tracking:d});if(b=g.dBa(b))if(b=g.Zd(b),b=g.Xd(b))a.B=g.bv(b,c)},a4=function(a,b,c){c=void 0===c?!0:c;
a.player.Ff("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&Y7a(a);c=[];d=new g.KA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.W({F:"div",K:"ytp-ce-shadow"}),g.lP(a.player,a.u.element,4),a.C=new g.NM(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Z7a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.lP(a.player,f.element,4);var h=new g.KA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);$7a(a,
f,e)}else g.Ez(new g.dw("buildEndscreenElement null",e))}a.player.xe(c);a.Ab()}},Y7a=function(a){var b=g.Oz(),c=g.Pz();
c&&b&&a.endscreen.visualElement&&g.gL(c,b,a.endscreen.visualElement)},Z7a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ga:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Ry||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-covering-image",X:b4(b)},{F:"div",K:"ytp-ce-covering-shadow-top"},{F:"a",K:"ytp-ce-covering-overlay",X:{href:c4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Go(b.title||"")},qa:b.title},{F:"div",K:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={F:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Ry||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-covering-image",X:b4(b)},{F:"div",K:"ytp-ce-covering-shadow-top"},{F:"a",K:"ytp-ce-covering-overlay",X:{href:c4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Go(b.title||"")},qa:b.title},{F:"div",K:"ytp-ce-playlist-count",
W:[{F:"div",K:"ytp-ce-playlist-icon"},{F:"div",K:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={F:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Ry||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",W:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},{F:"div",K:"ytp-ce-expanding-overlay-content",
W:[{F:"div",K:"ytp-ce-expanding-overlay-body",W:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{F:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],X:{href:c4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Go(b.title||"")},qa:b.title},b.subscribeButton?{F:"div",K:"ytp-ce-subscribe-container",W:[{F:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",K:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{F:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",X:b4(b)}]};c=new g.W(c);var d=g.Me(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.no(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.WQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ga:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Ry||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",W:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},{F:"div",K:"ytp-ce-expanding-overlay-content",
W:[{F:"div",K:"ytp-ce-expanding-overlay-body",W:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",K:"ytp-ce-website-title",X:{dir:g.Go(b.title||"")},qa:b.title},{F:"div",K:"ytp-ce-website-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],X:{href:c4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",X:b4(b)},{F:"div",K:"ytp-ce-expanding-icon",X:a8a(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",K:"ytp-ce-merchandise-price-container",W:[{F:"div",K:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({F:"div",K:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={F:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Ry||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",W:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},
{F:"div",K:"ytp-ce-expanding-overlay-content",W:[{F:"div",K:"ytp-ce-expanding-overlay-body",W:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",K:"ytp-ce-merchandise-title",X:{dir:g.Go(b.title||"")},qa:b.title},c,{F:"div",K:"ytp-ce-merchandise-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:c4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",X:b4(b)},{F:"div",K:"ytp-ce-merchandise-invideo-cta-container",
W:[{F:"div",K:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.no(c.element,"ytp-ce-placeholder");return c},b4=function(a){if(a.hQ)var b=a.hQ.thumbnails;
return a8a(b?b[b.length-1].url:null)},a8a=function(a){return a?{style:"background-image: url("+a+")"}:{}},$7a=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.no(b.element,"ytp-ce-force-expand"),d4(a,c.id,!0)):(g.po(b.element,"ytp-ce-force-expand"),g.po(b.element,"ytp-ce-element-hover"),d4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){b8a(a,b,c)});
b.Qa("mouseleave",function(){c8a(a,b,c)});
a.player.V().isMobile||b.Qa("click",function(){g.no(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){d8a(a,c,m)});
b.Qa("keypress",function(m){d8a(a,c,m)});
b.Qa("focus",function(){b8a(a,b,c)});
b.Qa("blur",function(){c8a(a,b,c)});
b.Qa("touchstart",function(){b8a(a,b,c)});
var l=g.Pe("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.po(b.element,"ytp-ce-element-hover");g.po(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.Pe("ytp-sb-subscribe",b.element));d(g.Pe("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},d8a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.mo(d,"ytp-ce-element");){g.mo(d,"subscribe-label")&&e8a(a,b);
if(g.mo(d,"ytp-ce-channel-subscribe"))return;d=g.bf(d)}if(!d||g.mo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])c8a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Z4)e8a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Zd(c4(a,b.targetUrl)),g.oN(g.Xd(c),void 0,b.sessionData);else{var e=g.aH(a.player.V())||a.player.getVideoData().D,f=function(){var h=c4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.Ou(h);e&&n&&(n.v||
n.list)?a.player.zm(n.v,l,n.list,!1,void 0,m||void 0):g.nN(h,l)};
e8a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},c4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.iH(a)+b}else return"";return b},b8a=function(a,b,c){g.mo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.no(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.fo(function(){g.no(b.element,"ytp-ce-element-hover")},200)).start():g.no(b.element,"ytp-ce-element-hover"),e4(a,c.K_),d4(a,c.id,!0))},c8a=function(a,b,c){g.po(b.element,"ytp-ce-element-hover");
g.po(b.element,"ytp-ce-force-expand");d4(a,c.id,!1)},d4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.ro(a.j[e].element,"ytp-ce-element-shadow-show",c)},e4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||$3(a))c&&c();else{b=f8a(a,b);var e=0,f=!1,h=new g.fo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Ax(b[a],d)}},e8a=function(a,b,c){e4(a,b.clickUrls,c);
(a=g.Pz())&&b.V_&&g.kL(a,b.visualElement)},f8a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(g8a(b[d],c));return a},g8a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},h8a=function(a){return"string"===typeof a?a:""},f4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},i8a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},g4=function(a){return a.value?a.value:null},h4=function(a){if(!a)return null;
var b=g.Zd(h8a(a.value));b=g.Xd(b);if(!b)return null;var c=f4(a.target,j8a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new i8a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},k8a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},n8a=function(a){if(!a)return null;
var b=f4(a.type,l8a),c=f4(a.trigger,m8a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=h4(a?a:null);return b?new k8a(b,c,a):null},o8a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},p8a=function(a,b){return g.lb(a.action,b)},q8a=function(a,b){this.context=a;
this.j=b},r8a=function(a){return a.customMessage?i4("div","iv-card-message",a.customMessage):""},j4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",K:"iv-card-image",X:{style:a},W:c}},s8a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(i4("li","",c.value));return{F:"ul",K:"iv-card-meta-info",W:b}},i4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Go(c);return{F:a,X:b,qa:c}},t8a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.bz&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.bz+");");c.dir=g.Go(a.customMessage);var d=[{F:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",K:"iv-card-link-icon"}));return{F:"div",Ga:b,X:c,W:d}},k4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Uh.click,5)}},u8a=function(a,b){this.merchant=a;
this.price=b},v8a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},w8a=function(a,b){return b?b:v8a(a)?"current":"new"},l4=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.sb=!1;this.Wa=new Map;this.Xa=new Map;this.context.G.addEventListener(g.MA("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.NA("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},m4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.AG(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.sb=!1});
a.context.j.Qa(b,"touchmove",function(){a.sb=!0})},x8a=function(a){var b;
return(null==(b=g.P(a,g.II))?0:b.url)?g.P(a,g.II).url:(a=g.P(a,g.GH))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},n4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
yU:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
LF:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},y8a=function(a,b,c){l4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Pa=this.Wb=this.B=this.isInitialized=!1;this.Aa=null;this.cards=[];this.zb=this.T=this.Ma=this.D=this.Va=this.j=null;this.ea=[];this.oa=this.J=this.Bf=this.Ka=null;this.I=0;this.Ba=new g.fo(function(){},c.Y.Ag?4E3:3E3);
g.H(this,this.Ba);this.kb=new g.fo(function(){});
g.H(this,this.kb);this.ya=new q8a(c,function(e,f,h,l,m,n){m4(d,e,f,h,l,m,n)});
this.Z=new g.W({F:"div",K:"iv-drawer",X:{id:"iv-drawer"},W:[{F:"div",K:"iv-drawer-header",X:{"aria-role":"heading"},W:[{F:"span",K:"iv-drawer-header-text"},{F:"button",Ga:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",K:"iv-drawer-content"}]});g.H(this,this.Z);this.C=this.Z.element;this.gb=new g.NM(this.Z,330);g.H(this,this.gb);this.Nb=g.Pe("iv-drawer-header-text",this.C);this.u=g.Pe("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Wb&&o4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Wb=d.B)&&p4(d)});
this.G.addEventListener("videodatachange",this.Tq.bind(this))},z8a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){o4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){p4(a)});
var c=b.headerText;g.df(a.Nb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ka=g.Lz(b.trackingParams);a.J=g.Lz(b.closeTrackingParams);a.Bf=g.Lz(b.iconTrackingParams)},A8a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.V().experiments.eb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.UA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Uh:{},Zm:null,fk:e.trackingParams?g.Lz(e.trackingParams):null,Bf:f&&f.trackingParams?g.Lz(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
bz:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};q4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.UA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:r4(a,c,b,f),sponsored:!1,Uh:n4(f,e,f.command),Zm:f.trackingParams?g.Lz(f.trackingParams):null,fk:e.trackingParams?g.Lz(e.trackingParams):null,Bf:l&&l.trackingParams?g.Lz(l.trackingParams):null,imageUrl:s4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.UA(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,bz:null,title:f.title?g.UA(f.title):"",customMessage:f.callToAction?g.UA(f.callToAction):"",url:g.P(f.command,g.II).url?h4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.P(f.command,g.II).url}):null,onClickCommand:null};q4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.UA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:r4(a,c,b,e),sponsored:!1,Uh:n4(e,f,e.endpoint),Zm:e.trackingParams?g.Lz(e.trackingParams):null,fk:f.trackingParams?g.Lz(f.trackingParams):null,Bf:l&&l.trackingParams?g.Lz(l.trackingParams):null,channelId:g.P(e.endpoint,t4).browseId,customMessage:e.customText?g.UA(e.customText):null,profileImageUrl:s4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.UA(e.channelName):"",metaInfo:[e.subscriberCountText?g.UA(e.subscriberCountText):""],url:h4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.P(e.endpoint,t4).canonicalBaseUrl?g.P(e.endpoint,t4).canonicalBaseUrl:"/channel/"+g.P(e.endpoint,t4).browseId}),onClickCommand:null};q4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.UA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:r4(a,c,b,e),sponsored:!1,Uh:n4(e,f,e.action),Zm:e.trackingParams?g.Lz(e.trackingParams):null,fk:f.trackingParams?g.Lz(f.trackingParams):null,Bf:l&&l.trackingParams?g.Lz(l.trackingParams):null,JB:s4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.UA(e.customMessage):null,playlistVideoCount:g.UA(e.playlistVideoCount),title:e.playlistTitle?g.UA(e.playlistTitle):"",metaInfo:[e.channelName?g.UA(e.channelName):
"",e.videoCountText?g.UA(e.videoCountText):""],url:h4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:x8a(e.action)}),onClickCommand:null};q4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.UA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:r4(a,c,b,e),sponsored:!1,Uh:n4(e,f,e.action),Zm:e.trackingParams?g.Lz(e.trackingParams):null,fk:f.trackingParams?g.Lz(f.trackingParams):null,Bf:l&&l.trackingParams?g.Lz(l.trackingParams):null,JB:s4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.UA(e.lengthString):null,customMessage:e.customMessage?g.UA(e.customMessage):null,title:e.videoTitle?g.UA(e.videoTitle):"",metaInfo:[e.channelName?g.UA(e.channelName):
"",e.viewCountText?g.UA(e.viewCountText):""],isLiveNow:!!e.badge,url:h4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:x8a(e.action)}),onClickCommand:null};q4(a,b)}}}}}a.I++},s4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},r4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},C8a=function(a,b){if(b=B8a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.af(b.eI),g.sb(a.cards,b),a.MC(),u4(a)},o4=function(a,b,c){if(!a.B){a.gb.show();
a.Va=new g.fo(function(){g.no(a.context.G.getRootNode(),g.rV.IV_DRAWER_OPEN)},0);
a.Va.start();a.Aa=g.by(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Pz();d&&a.Ka&&a.J&&g.iL(d,[a.Ka,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.XR||(f.XR=!0,D8a(a.context.logger,f.card.Uh.impression,b)),d&&g.iL(d,[f.card.Zm]);R3(a.G);c&&(a.D=new g.fo(function(){a.Ma=a.T;a.zb.focus()},330),a.D.start())}},p4=function(a){a.B&&(a.gb.hide(),g.cy(a.Aa),a.Aa=null,g.po(a.context.G.getRootNode(),g.rV.IV_DRAWER_OPEN),a.B=!1,R3(a.G),a.D&&a.D.stop(),a.D=new g.fo(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},
F8a=function(a){g.oo(a.element,[g.rV.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.lP(a.G,a.C,5);E8a(a);a.T=g.Pe("ytp-cards-button",a.G.getRootNode());a.zb=g.Pe("iv-drawer-close-button",a.C);a.isInitialized=!0},E8a=function(a){var b=g.Pe("iv-drawer-close-button",a.C);
a.context.j.Qa(b,"click",a.qZ,a);a.context.j.Qa(a.u,"touchend",function(){a.Ba.start()});
a.context.j.Qa(a.u,"scroll",a.EZ,a);a.context.u.subscribe("onHideControls",function(){a.Pa=!0});
a.context.u.subscribe("onShowControls",function(){a.Pa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Pa=g.mo(a.G.getRootNode(),"ytp-autohide")});
a.ea.push(g.vy("iv-button-shown",a.g0,a));a.ea.push(g.vy("iv-button-hidden",a.f0,a));a.ea.push(g.vy("iv-teaser-shown",a.XV,a));a.ea.push(g.vy("iv-teaser-hidden",a.h0,a));a.ea.push(g.vy("iv-teaser-clicked",a.WV,a))},G8a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.P(b.onClickCommand,g.p4a))?void 0:c.targetId)?(a.oa=b,!0):!1},H8a=function(a,b){a.oa=b;
var c=a.G.getVideoData();if(!c)return!1;c=a.G.S("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.IH(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.P(h[0],g.SLa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
q4=function(a,b){if(!G8a(a,b)||H8a(a,b)){var c=I8a(a,b);
if(c){var d={card:b,eI:c.element,XR:!1};if(!b.onClickCommand){a.isInitialized||F8a(a);C8a(a,b.id);var e=J8a(a,d);g.Bb(a.cards,e,0,d);c.Ca(a.u,e);a.MC()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,u4(a),K8a(a,d),o4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&L8a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){L8a(a,d)}),u4(a))}}},I8a=function(a,b){switch(b.type){case "simple":var c=a.ya;
var d=b.displayDomain?{F:"div",K:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=t8a(b);d={F:"div",Ga:["iv-card"],W:[{F:"a",K:"iv-click-target",X:{href:b.url?g4(b.url)||"":""},W:[j4(b.imageUrl,d),{F:"div",K:"iv-card-content",W:[i4("h2",void 0,b.title),e]}]}]};d=new g.W(d);k4(c,g.Ne("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.ya;d={F:"div",Ga:["iv-card","iv-card-channel"],W:[{F:"a",Ga:["iv-click-target"],X:{href:g4(b.url)||"","data-ytid":b.channelId},W:[j4(b.profileImageUrl),
{F:"div",K:"iv-card-content",W:[r8a(b),{F:"h2",K:"iv-card-primary-link",qa:b.title},s8a(b)]}]}]};d=new g.W(d);k4(c,g.Ne("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.ya;d={F:"div",Ga:["iv-card","iv-card-playlist"],W:[{F:"a",K:"iv-click-target",X:{href:g4(b.url)||""},W:[j4(b.JB,{F:"div",K:"iv-card-image-overlay",W:[{F:"span",K:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{F:"div",K:"iv-card-content",W:[r8a(b),i4("h2","iv-card-primary-link",b.title),s8a(b)]}]}]};
d=new g.W(d);k4(c,g.Ne("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.ya;var f=!g.qb(b.offers);d=["iv-card"];e="";var h=t8a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({F:"div",K:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({F:"div",K:"iv-card-offer-merchant",qa:h.merchant}),h={F:"div",W:f});f=b.url?g4(b.url)||"":"";d={F:"div",Ga:d,X:{tabindex:"0"},W:[{F:"a",Ga:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{F:"div",K:"iv-card-content",W:[b.sponsored?{F:"div",K:"iv-card-sponsored",W:["Sponsored",{F:"div",K:"iv-ad-info-container",W:[{F:"div",K:"iv-ad-info",qa:"{{adInfo}}"},{F:"div",K:"iv-ad-info-icon-container",W:[{F:"div",K:"iv-ad-info-icon"},{F:"div",K:"iv-ad-info-callout"}]}]}]}:"",{F:"a",K:"iv-click-target",X:{href:f},W:[i4("h2",e,b.title),h]}]}]};d=new g.W(d);e=g.Ve("span");g.df(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Td(e,"adInfo");k4(c,g.Ne("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.ya;d=b.videoDuration?{F:"span",K:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{F:"span",Ga:["yt-badge","yt-badge-live"],qa:"LIVE NOW"}:null;f={F:"div",Ga:["iv-card","iv-card-video"],W:[{F:"a",K:"iv-click-target",X:{href:(null==(h=b.url)?void 0:g4(h))||""},W:[j4(b.JB,d),{F:"div",K:"iv-card-content",W:[r8a(b),i4("h2","iv-card-primary-link",b.title),s8a(b),e]}]}]};d=new g.W(f);k4(c,g.Ne("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.G.V().experiments.eb("web_rounded_containers")&&g.no(b.element,"ytp-rounded-info");return b},J8a=function(a,b){if(0===a.cards.length)return 0;
a=g.nb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},M8a=function(a){return a.j?"productListing"===a.j.card.type:g.Uk(a.cards,function(b){return"productListing"===b.card.type})},u4=function(a){g.ro(a.G.getRootNode(),"ytp-cards-shopping-active",M8a(a))},L8a=function(a,b){if(!g.mo(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Pz(),d=a.j?a.j.card.Bf:a.Bf;
c&&d&&g.jL(c,[d]);a.j=b;u4(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Bx(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.kb.isActive()||((!a.B||!a.Ba.isActive()&&a.Pa)&&K8a(a,b),a.kb.start(910+b.card.teaserDurationMs))}},K8a=function(a,b){a.Z.tb?(b=new W3([0,
a.u.scrollTop],[0,b.eI.offsetTop],600,L7a),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.aM(a.Z,!0),a.u.scrollTop=b.eI.offsetTop,g.aM(a.Z,!1))},v4=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},B8a=function(a,b){return g.lb(a.cards,function(c){return c.card.id===b})},w4=function(a,b,c){l4.call(this,a,b);
this.annotation=c;this.isActive=!1},N8a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},x4=function(a,b,c){w4.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},O8a=function(a,b){var c=void 0===c?0:c;
var d=J7a(b).width;g.Nl(b,d);c=new R7a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,K7a);g.H(a,c);a.context.B.Qa(c,"begin",function(){g.Tl(b,!0)});
c.play()},R8a=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ga:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({F:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.WQ(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.Ca(d));var f=a.createElement({F:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Tl(h,!1);a.context.Y.S("web_rounded_containers")&&g.no(h,"ytp-rounded-branding-context");var l=a.createElement({F:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.Hl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.fo(function(){P8a(a,h,l)},500);
g.H(a,a.B);a.context.j.Qa(a.element,"mouseover",function(){Q8a(a,h,l,f,b.image_height)});
a.context.j.Qa(a.element,"mouseout",function(){a.B.start()})}},Q8a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Sl(b);a.j||(b.style.width=g.Ml(f.width,!0),c.style.width=g.Ml(f.width,!0));g.Hl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Hl(d,"right","1px");a.C=!0;g.Tl(b,!0);a.D=new g.fo(function(){g.no(this.element,"iv-branding-active")},0,a);
a.D.start()}},P8a=function(a,b,c){g.po(a.element,"iv-branding-active");
a.I=new g.fo(function(){g.Tl(b,!1);a.j||(c.style.width=g.Ml(0,!0))},250);
a.I.start();a.C=!1},S8a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},T8a=function(a,b,c){w4.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.Z=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ga:["iv-promo-contents"]});this.D=new g.fo(function(){d.j.setAttribute("aria-hidden","true");g.Tl(d.B,!1);g.Tl(d.u,!0)},700,this);
g.H(this,this.D)},V8a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.He(),f=b.image_url;if(f){var h=a.createElement({F:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",K:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",K:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&m4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",K:"iv-promo-txt"}),g.ne(f,g4(e)),a.j=f):a.j=a.createElement({F:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",W:[{F:"strong",
qa:b.text_line_1}]});var m=a.createElement({F:"p",W:[{F:"span",K:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ga:["iv-button","iv-promo-button"],W:[{F:"span",K:"iv-button-content",qa:f}]});var p=a.createElement({F:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&m4(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.no(a.j,
"iv-click-target");e&&m4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",W:[{F:"span",qa:b.text_line_1}]}),m=a.createElement({F:"p",W:[{F:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ga:["yt-badge","iv-promo-badge-live"],qa:"LIVE NOW"})),g.no(a.j,"iv-click-target"),e&&m4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);
p&&a.J.appendChild(p);c=a.createElement({F:"div",K:"iv-promo-actions"});a.u=a.createElement({F:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Qa(a.u,"click",function(q){U8a(a,5E3,q)});
c.appendChild(a.u);g.Tl(a.u,!1);a.context.j.Qa(a.element,"mouseover",a.p_,a);a.context.j.Qa(a.element,"mouseout",a.o_,a);a.context.j.Qa(a.element,"touchend",function(q){U8a(a,5E3,q)});
a.B=a.createElement({F:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.k_:a.j_,a);c.appendChild(a.B);g.oo(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},U8a=function(a,b,c){c.stopPropagation();
W8a(a);X8a(a,b);a.j.focus()},Y8a=function(a){a.isCollapsed||a.T||a.C||(g.no(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},W8a=function(a){a.D.stop();
a.isCollapsed&&(g.qo(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Tl(a.u,!1),g.Tl(a.B,!0))},X8a=function(a,b){a.C||(a.C=g.Af(function(){Z8a(this);
Y8a(this)},b,a))},Z8a=function(a){a.C&&(g.D.clearTimeout(a.C),a.C=null)},$8a=function(a){this.G=a},D8a=function(a,b,c){b&&(c?y4(a,b.map(function(d){return g.Yn(d,c)})):y4(a,b))},y4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Ax(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},a9a=function(a){g.TP.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new $8a(this.player);this.D=new g.vE(this);this.C=this.ao=null;this.events=new g.vE(this);this.J=this.j=null;this.T=[];g.H(this,this.D);this.D.N(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.D.N(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.D.N(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.D.N(this.player,"resize",function(d){b.ma("resize",d)});
this.D.N(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.YV,this);this.subscribe("resize",this.LE,this);this.player.V().ya.subscribe("vast_info_card_add",this.gT,this);g.H(this,this.events);this.Z=this.createElement({F:"div",K:"video-custom-annotations"});this.u=new g.W({F:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.lP(this.player,this.u.element,4);this.u.hide();this.B=new g.W({F:"div",Ga:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({F:"div",K:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Du()&&this.load();var c=this.createElement({F:"style"});(g.Le("HEAD")[0]||document.body).appendChild(c);g.db(this,function(){g.af(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},b9a=function(a){a=a.createElement({F:"div",
Ga:["annotation","annotation-type-custom"]});g.Tl(a,!1);return a},c9a=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.aM(a.u,b);g.aM(a.B,b)},d9a=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(d9a(a,e))}return c},h9a=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.V().ya.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Wu(h)&&h.responseXML?h.responseXML:null)&&e9a(a,h)}};
g.bw()&&(d.onFinish=f9a(a,d.onFinish));d.postParams={ic_only:"1"};g9a(d,c);g.bv(b.Wa,d)}}},g9a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.fz&&(a.postParams.ic_coll=b.fz);b.SC&&(a.postParams.ic_xml=b.SC);b.MB&&(a.postParams.ic_track=b.MB)},i9a=function(a){var b=new g.W({F:"div"});
g.Tl(b.element,!1);var c=new y8a(a.player,b.element,z4(a));g.H(c,b);b.Ca(a.u.element);c.yB();return c},z4=function(a){if(!a.J){var b=new S7a(a);
g.H(a,b);var c=new g.Mj(a);g.H(a,c);a.J=new S8a(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Mh)}return a.J},e9a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)){var e=d[0].getAttribute("itct");if(e&&(d=g.Pz())){var f=g.Oz();f&&(e=[g.Lz(e)],g.Cu("safe_logging_library_killswitch")?g.Sz(void 0,d,f,e):g.Iu(g.Sz)(void 0,d,f,e))}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){e=d9a(a,b[d]);f=null;try{if(e){var h=e.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=f4(e.type,j9a),p=f4(e.style,k9a),q=h8a(e.data),r=0!==q.length?JSON.parse(q):{};var w=e.action;e=n8a;if(null==w)var x=null;else if(g.Ka(w)){l=
[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var C=e(B.value);C&&l.push(C)}x=l}else{var G=e(w);x=G?[G]:[]}f=m&&n?new o8a(m,n,p,x,r):null}else f=null}catch(S){}if(f)if("branding"===f.type||"promotion"===f.type){e=a;l=f;var F=b9a(e),K=null;switch(l.type){case "branding":if(e.player.V().Bd)break;e.u.element.appendChild(F);K=new x4(F,z4(e),l);break;case "promotion":g.lP(e.player,F,4),K=new T8a(F,z4(e),l)}K&&K.yB();if(e=K)g.H(a,e),a.I[f.id]=e}else if("card"===f.type||"drawer"===f.type){a.j||(a.j=
i9a(a),g.H(a,a.j));if("card"===f.type){c=a.j;var L=f&&f.data&&f.data.card_type;e=f.data;if(L)switch(l=e.tracking||{},l={impression:l.impression,click:l.click,close:l.close,yU:l.teaser_impression,LF:l.teaser_click},F=e.tracking_params||{},K=null,L){case "collaborator":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Zm:F.card?g.Lz(F.card):
null,fk:F.teaser?g.Lz(F.teaser):null,Bf:F.icon?g.Lz(F.icon):null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:h4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};q4(c,f);break;case "playlist":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,
sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Zm:F.card?g.Lz(F.card):null,fk:F.teaser?g.Lz(F.teaser):null,Bf:F.icon?g.Lz(F.icon):null,JB:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:h4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};q4(c,f);break;case "productListing":e.signin_url&&(K=h4({target:"current",value:e.signin_url}));L=
[];for(var N=e.offers||[],ba=0;ba<N.length;ba++)L.push(new u8a(g.De(N[ba].merchant),g.De(N[ba].price)));f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Zm:F.card?g.Lz(F.card):null,fk:F.teaser?g.Lz(F.teaser):null,Bf:F.icon?g.Lz(F.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,
bz:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:h4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),A9a:K,z9a:e.signin_title?e.signin_title:void 0,y9a:e.signin_message?e.signin_message:void 0,offers:L,onClickCommand:null};q4(c,f);break;case "simple":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||
!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Zm:F.card?g.Lz(F.card):null,fk:F.teaser?g.Lz(F.teaser):null,Bf:F.icon?g.Lz(F.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,bz:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:h4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};q4(c,f);break;case "video":f=
{id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Zm:F.card?g.Lz(F.card):null,fk:F.teaser?g.Lz(F.teaser):null,Bf:F.icon?g.Lz(F.icon):null,JB:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:h4({pause_on_navigation:e.pause_on_navigation,
target:e.target||"new",value:e.url}),onClickCommand:null},q4(c,f)}}else z8a(a.j,f);c=!0}}c&&(R3(a.player),a.LE())},l9a=function(a,b){var c=!1;
a.j||(a.j=i9a(a),g.H(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(A8a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.UA(b.headerText):"",g.df(c.Nb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ka=b.trackingParams?g.Lz(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Lz(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Bf=b.icon.infoCardIconRenderer.trackingParams?
g.Lz(b.icon.infoCardIconRenderer.trackingParams):null,R3(a.player),a.LE())},m9a=function(a,b,c,d,e){if(!a.player.V().Bd){var f=[];
b.navigationEndpoint&&g.P(b.navigationEndpoint,t4)&&g.P(b.navigationEndpoint,t4).browseId&&f.push(new k8a("openUrl","click",new i8a("/channel/"+g.P(b.navigationEndpoint,t4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.P(b.subscribeButton,
g.YI)){d.channel_id=g.P(b.subscribeButton,g.YI).channelId;var l;b=g.P(b.subscribeButton,g.YI);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.UA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.UA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.UA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.UA(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.P(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.M2))?void 0:m.url)||"";l={subscribeText:g.UA(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.UA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new o8a(c,"branding","branding",f,d);l=b9a(a);a.u.element.appendChild(l);f=new x4(l,z4(a),f);f.yB();g.H(f,f);a.I[c]=f}},f9a=function(a,b){return function(){var c=g.ya.apply(0,arguments);
a.isDisposed()||a.T.push(g.ao.Ih(function(){b.apply(null,g.u(c))}))}},n9a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.eP.prototype.Bx=g.ca(19,function(a,b){var c=g.kQ(this.ub());c&&c.Bx(a,b)});
var T3={},U3=null;g.Ua(W3,g.Co);g.k=W3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Tc())return!1;V3(this);this.startTime=a=g.Ta();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.HE();this.Ik("play");-1==this.j&&this.Ik("resume");this.j=1;var b=g.Oa(this);b in T3||(T3[b]=this);N7a();O7a(this,a);return!0};
g.k.stop=function(a){V3(this);this.j=0;a&&(this.progress=1);P7a(this,this.progress);this.Ik("stop");this.NA()};
g.k.pause=function(){this.Tc()&&(V3(this),this.j=-1,this.Ik("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Ik("destroy");W3.kf.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.zG=function(){this.Ik("animate")};
g.k.Ik=function(a){this.dispatchEvent(new Q7a(a,this))};
g.Ua(Q7a,g.fb);g.Ua(X3,W3);X3.prototype.C=function(){};
X3.prototype.zG=function(){this.C();X3.kf.zG.call(this)};
X3.prototype.NA=function(){this.C();X3.kf.NA.call(this)};
X3.prototype.HE=function(){this.C();X3.kf.HE.call(this)};
g.Ua(R7a,X3);R7a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var t4=new g.gp("browseEndpoint");g.v(S7a,g.E);g.k=S7a.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.by(a,b,c);this.j.push(a);return a};
g.k.oE=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.cpa(a,b,c);this.j.push(a);return a};
g.k.Ac=function(a){g.cy(a);g.sb(this.j,a)};
g.k.gg=function(){g.cy(this.j);this.j.length=0};
g.k.ra=function(){this.gg();g.E.prototype.ra.call(this)};g.v(V7a,g.TP);g.k=V7a.prototype;g.k.load=function(){g.TP.prototype.load.call(this);if(!$3(this)){var a=g.eBa(this.player.getVideoData());a?(a=U7a(a,W7a(this)),a4(this,a,!1)):X7a(this)}};
g.k.unload=function(){a4(this,null);this.B&&(this.B.abort(),this.B=null);g.TP.prototype.unload.call(this)};
g.k.Vg=function(a,b){return $3(this)?"loadCustomEndscreenRenderer"===a?(a=U7a(b,"new"),a4(this,a),!0):null:null};
g.k.getOptions=function(){return $3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ab=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<o9a.length;f++){var h=Math.abs(b.width-o9a[f]);if(-1===e||d>=h)e=f,d=h}d=p9a[e];this.u&&g.Hl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Rl(e.element,m,f);g.Nl(e.element,n,p);this.ea&&(g.qo(e.element,q9a),256<m||256<f?g.no(e.element,"ytp-ce-large-round"):96<m||96<f?g.no(e.element,"ytp-ce-medium-round"):g.no(e.element,"ytp-ce-small-round"));g.qo(e.element,r9a);m=h.left+h.width/2;h=h.top+l/2;g.no(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.qo(e.element,p9a);g.no(e.element,d);(e=g.Me(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Hl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())e4(this,this.endscreen.impressionUrls),(a=g.Pz())&&this.endscreen.visualElement&&g.hL(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.no(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.no(b,"ytp-ce-shown");e4(this,c.impressionUrls);(b=g.Pz())&&g.hL(b,c.visualElement);this.player.V().D&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.po(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.po(b,"ytp-ce-shown");this.player.V().D&&this.player.Oa("endscreenelementhidden",a)}};
g.k.Q3=function(a){var b=this;a.target===window&&(new g.fo(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.qo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var o9a=[346,426,470,506,570,640,853,1280,1920],p9a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),r9a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],q9a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var j8a={ama:"current",uJa:"new"};var l8a={CLOSE:"close",YMa:"openUrl",SUBSCRIBE:"subscribe"},m8a={dha:"click",CLOSE:"close",Mva:"hidden",qSa:"rollOut",rSa:"rollOver",AUa:"shown"};o8a.prototype.He=function(){var a=p8a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var k9a={zca:"anchored",yV:"branding",CHANNEL:"channel",Qla:"cta",Pva:"highlightText",Uza:"label",PLAYLIST:"playlist",QPa:"popup",aXa:"speech",SUBSCRIBE:"subscribe",g_a:"title",VIDEO:"video",H5a:"website"},j9a={yV:"branding",cfa:"card",coa:"drawer",Ova:"highlight",FFa:"marker",SQa:"promotion",TEXT:"text",A6a:"widget"};g.v(l4,g.E);g.k=l4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.KA(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.Xa.set(a,e);this.context.G.xe([a])};
g.k.yB=function(){this.context.u.subscribe("resize",this.MC,this)};
g.k.AG=function(a,b,c,d,e,f){if(this.sb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.af(this.element)};
g.k.MC=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=g4(a);if(f){var h=w8a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.Ou(f||"");m&&n&&(n.v||n.list)?e.context.G.zm(n.v,b,n.list,!1):g.oN(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);y4(this.context.logger,c,l,d);v8a(f)||(c=g.Pz(),d=b.itct,c&&d&&g.kL(c,g.Lz(d)))}};
g.k.ra=function(){this.Wa.clear();this.Xa.clear();g.E.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.v(y8a,l4);g.k=y8a.prototype;g.k.Tq=function(){this.oa&&q4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Sl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.MC=function(){var a=this.isAvailable();g.Tl(this.element,a);g.ro(this.context.G.getRootNode(),g.rV.IV_DRAWER_ENABLED,a);R3(this.G)};
g.k.destroy=function(){this.G.Bx(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.wy(this.ea);g.cy(this.Aa);this.Va&&this.Va.dispose();this.D&&this.D.dispose();l4.prototype.destroy.call(this)};
g.k.qZ=function(){if(this.B){y4(this.context.logger,v4(this).Uh.close);var a=g.Pz();a&&this.J&&g.kL(a,this.J);p4(this)}};
g.k.EZ=function(){g.ro(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.g0=function(){var a=g.Pz(),b=v4(this);b=b?b.Bf:this.Bf;a&&b&&g.iL(a,[b])};
g.k.f0=function(){var a=g.Pz(),b=v4(this);b=b?b.Bf:this.Bf;a&&b&&g.jL(a,[b])};
g.k.XV=function(){var a=v4(this);y4(this.context.logger,a.Uh.yU);var b=g.Pz();b&&a&&g.iL(b,[a.fk,a.Bf])};
g.k.h0=function(){var a=g.Pz(),b=v4(this);a&&b&&g.jL(a,[b.fk])};
g.k.WV=function(a){var b=v4(this),c=g.Pz();this.j?a?(a=this.context.logger,y4(a,b.Uh.LF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.fk&&g.kL(c,b.fk)):(a=this.context.logger,y4(a,b.Uh.LF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Bf&&g.kL(c,b.Bf)):(a=this.context.logger,y4(a,b.Uh.LF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Bf&&g.kL(c,this.Bf))};g.v(w4,l4);w4.prototype.yB=function(){l4.prototype.yB.call(this);N8a(this)};
w4.prototype.show=function(){l4.prototype.show.call(this);var a=g.Pz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.iL(a,[g.Lz(b.itct)])};
w4.prototype.hide=function(){l4.prototype.hide.call(this);var a=g.Pz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.jL(a,[g.Lz(b.itct)])};g.v(x4,w4);
x4.prototype.show=function(){if(!this.isActive){w4.prototype.show.call(this);if(!this.J){g.no(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ga:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Tl(this.u,!1);var b=this.createElement({F:"button",Ga:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.He();c&&m4(this,
b,c,this.annotation.id,a.session_data);R8a(this,a);this.J=!0}g.Tl(this.element,!0);this.isActive=!0;this.u&&(O8a(this,this.u),g.no(this.context.G.getRootNode(),"ytp-branding-shown"))}};
x4.prototype.hide=function(){this.isActive&&(w4.prototype.hide.call(this),g.Tl(this.element,!1),this.isActive=!1,g.po(this.context.G.getRootNode(),"ytp-branding-shown"))};
x4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);w4.prototype.destroy.call(this)};g.v(T8a,w4);g.k=T8a.prototype;g.k.show=function(){this.isActive||(w4.prototype.show.call(this),this.Z||(V8a(this),this.Z=!0),g.Tl(this.element,!0),g.Af(function(){g.po(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,Z8a(this),W8a(this),X8a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.no(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.AG=function(a,b,c,d,e,f){return this.isCollapsed?!1:w4.prototype.AG.call(this,a,b,c,d,e,f)};
g.k.p_=function(a){this.T=!0;U8a(this,500,a)};
g.k.o_=function(){this.T=!1;Y8a(this)};
g.k.j_=function(a){a.stopPropagation();this.hide()};
g.k.k_=function(a){a.stopPropagation();Z8a(this);this.isCollapsed=!0;g.no(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();w4.prototype.destroy.call(this)};g.v(a9a,g.TP);g.k=a9a.prototype;g.k.Vg=function(a,b){if(!n9a(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.K2a(b))&&e9a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(C8a(this.j,b),R3(this.player)),!0}return null};
g.k.getOptions=function(){return n9a(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Du=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.Z?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.AN||a.ya.get(b.videoId)||g.eJ(b)||g.fJ(b)?!0:!1};
g.k.LE=function(){if(this.B){var a=this.player.fb().getVideoContentRect(!0);g.Rl(this.B.element,a.width,a.height);g.Nl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Hj();a=this.j;b=b.width;g.ro(a.C,"iv-drawer-small",426>=b);g.ro(a.C,"iv-drawer-big",1280<=b)}};
g.k.YV=function(a){c9a(this,a.state);g.U(a.state,2)&&(this.Oi()&&this.Ym()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Bx(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Wu(h)&&h.responseXML?h.responseXML:null)&&(e9a(b,h),g.no(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.TP.prototype.load.call(this);c9a(this,this.player.Gb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.bw()&&(a=f9a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().ya.get(d);f&&g9a(e,f);f=f&&(f.SC||f.fz);if(!c.Su||f)c.Wa?this.C=g.bv(c.Wa,e):(this.ao=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.ao));
g.lP(this.player,this.B.element,4);this.LE();(f=g.eJ(c))&&l9a(this,f);(f=g.fJ(c))&&f.featuredChannel&&m9a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&(this.ao&&(this.player.removeEventListener("videodatachange",this.ao),this.ao=null),this.C=g.bv(b.Wa,a))};
g.k.unload=function(){this.player.Ff("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,R3(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.TP.prototype.unload.call(this);this.B.detach();this.ao&&(this.player.removeEventListener("videodatachange",this.ao),this.ao=null)};
g.k.gT=function(a){a===this.player.getVideoData().videoId&&(this.loaded?h9a(this):this.load())};
g.k.Oi=function(){return!!this.j&&this.j.isAvailable()};
g.k.Ym=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Oi();this.j&&(a?c?o4(this.j,c,b):o4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):p4(this.j))};
g.k.Bx=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().ya.unsubscribe("vast_info_card_add",this.gT,this);g.po(this.player.getRootNode(),g.rV.IV_DRAWER_OPEN);for(var a=this.T,b=g.ao,c=0,d=a.length;c<d;c++)b.Cl(a[c]);this.T.length=0;g.TP.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.SP("annotations_module",a9a);g.SP("creatorendscreen",V7a);})(_yt_player);
